# SPDX-License-Identifier: Apache-2.0
"""Generate the public glossary from its machine-readable source."""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from typing import TYPE_CHECKING, TypedDict, cast

if TYPE_CHECKING:
    from collections.abc import Sequence

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "glossary.toml"
OUTPUT = ROOT / "docs" / "glossary.md"


class Term(TypedDict):
    """One glossary-source entry."""

    term: str
    definition: str
    source: str
    status: str


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render(source: Path = SOURCE) -> str:
    """Render deterministic Markdown from the glossary TOML source."""
    raw = tomllib.loads(source.read_text(encoding="utf-8"))
    terms = cast("list[Term]", raw["term"])
    names = [item["term"].casefold() for item in terms]
    if len(names) != len(set(names)):
        message = "glossary terms must be unique ignoring case"
        raise ValueError(message)
    for item in terms:
        if (
            not item["term"].strip()
            or not item["definition"].strip()
            or item["status"] not in {"accepted", "planned", "deprecated"}
            or not item["source"].strip()
        ):
            message = f"invalid glossary entry: {item!r}"
            raise ValueError(message)
    ordered = sorted(terms, key=lambda item: item["term"].casefold())
    rows = [
        "<!-- status: implemented -->",
        "<!-- generated by scripts/generate_glossary.py; do not edit directly -->",
        "",
        "# SOVA glossary",
        "",
        "This glossary is generated from `docs/glossary.toml`. Accepted terms come",
        "from controlling decisions. Topic 03 reconciled the shared domain language;",
        "the generator check makes later semantic drift visible in CI.",
        "",
        "| Term | Definition | State | Source |",
        "|---|---|---|---|",
    ]
    for term in ordered:
        source_link = f"[source](./{term['source']})"
        rows.append(
            "| `{term}` | {definition} | {status} | {source} |".format(
                term=_escape(term["term"]),
                definition=_escape(term["definition"]),
                status=_escape(term["status"]),
                source=source_link,
            )
        )
    rows.append("")
    return "\n".join(rows)


def build_parser() -> argparse.ArgumentParser:
    """Build the generator command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the generated file is stale",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Generate or verify the glossary."""
    args = build_parser().parse_args(argv)
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print("GLOSSARY_CHECK=FAILED: run python scripts/generate_glossary.py")
            return 1
        print("GLOSSARY_CHECK=PASS")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"WROTE={OUTPUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
