# SPDX-License-Identifier: Apache-2.0
"""Generate the public attack-taxonomy reference from packaged contract data."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from sova.contracts.taxonomy import AttackTaxonomy, load_attack_taxonomy

if TYPE_CHECKING:
    from collections.abc import Sequence

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "taxonomy" / "sova-attack-taxonomy.md"


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render(taxonomy: AttackTaxonomy | None = None) -> str:
    """Render deterministic Markdown from the validated taxonomy."""
    taxonomy = taxonomy or load_attack_taxonomy()
    rows = [
        "<!-- status: implemented -->",
        "<!-- generated by scripts/generate_taxonomy.py; do not edit directly -->",
        "",
        f"# SOVA attack taxonomy {taxonomy.version}",
        "",
        f"- Identifier: `{taxonomy.identifier}`",
        f"- Status: `{taxonomy.status}`",
        f"- Owner: {taxonomy.owner}",
        f"- Release date: {taxonomy.released}",
        "",
        "The standard profile contains every active taxon below. External mappings",
        "are version-pinned interoperability references. Relationship is the SOVA",
        "taxon relative to the external entry; mappings do not imply endorsement.",
        "",
        "| ID | Native class | Status | External mappings |",
        "|---|---|---|---|",
    ]
    for taxon in taxonomy.taxa:
        mappings = "; ".join(
            f"[{mapping.identifier}]({mapping.url}) "
            f"({mapping.framework} {mapping.catalog_version}, {mapping.relationship.value})"
            for mapping in taxon.mappings
        )
        rows.append(
            f"| `{taxon.identifier}` | {_escape(taxon.title)} | "
            f"`{taxon.status.value}` | {mappings or 'None'} |"
        )
    rows.extend(["", "## Definitions", ""])
    for taxon in taxonomy.taxa:
        rows.extend(
            [
                f"### {taxon.identifier}: {taxon.title}",
                "",
                taxon.definition,
                "",
            ]
        )
    rows.extend(
        [
            "## Standard profile",
            "",
            "```text",
            *taxonomy.standard_profile,
            "```",
            "",
            "For governance, retirement, and custom-profile rules, see the",
            "[taxonomy README](README.md) and",
            "[ADR-0008](../decisions/0008-topic-03-domain-contracts.md).",
            "",
        ]
    )
    return "\n".join(rows)


def build_parser() -> argparse.ArgumentParser:
    """Build the generator command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the generated file is stale",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Generate or verify the taxonomy reference."""
    args = build_parser().parse_args(argv)
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print("TAXONOMY_CHECK=FAILED: run python scripts/generate_taxonomy.py")
            return 1
        print("TAXONOMY_CHECK=PASS")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"WROTE={OUTPUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
